# Generated by Django 4.2.11 on 2024-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='template',
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='filename',
            field=models.CharField(default='default_template.html', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
