# Generated by Django 4.2.11 on 2025-01-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit', '0052_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='C74DfZQdCuRDIUFVnEivU5rn9a0QFIpU', editable=False, max_length=32, unique=True),
        ),
    ]
